-- V1__criar_tabelas.sql (H2 + Oracle mode)
create table equipamento (
  id bigint generated by default as identity primary key,
  tipo varchar(40) not null,
  descricao varchar(120) not null
);

create table professor (
  id bigint generated by default as identity primary key,
  nome varchar(120) not null,
  email_institucional varchar(160) unique
);

create table reserva (
  id bigint generated by default as identity primary key,
  equipamento_id bigint not null,
  professor_id   bigint not null,
  sala varchar(20) not null,
  retirada timestamp not null,
  entrega  timestamp not null,
  constraint fk_reserva_equipamento foreign key (equipamento_id) references equipamento(id),
  constraint fk_reserva_professor  foreign key (professor_id)  references professor(id),
  constraint ck_reserva_periodo check (entrega > retirada)
);

create index idx_reserva_equipamento on reserva (equipamento_id);
create index idx_reserva_professor  on reserva (professor_id);
